backend = "wal"
palette = 'dark16'
theshold = 20
check_contrast = true

[templates]
eww.template = 'eww-colors.scss'
eww.target = '~/.config/eww/colors.scss'

rofi.template = 'rofi-dark-colors.rasi'
rofi.target = '~/.config/rofi/rofi-dark-colors.rasi'

kitty.template = 'kitty-colors.conf'
kitty.target = '~/.config/kitty/kitty-colors.conf'

swaync.template = 'swaync-colors.css'
swaync.target = '~/.config/swaync/style.css'

swayosd.template = 'swayosd.css'
swayosd.target = '~/.config/swayosd/style.css'

conky.template = 'conky_sidebar.conf'
conky.target = '~/modified-zenities/.config/conky/conky_sidebar.conf'

conky_lua.template = 'grouped_processes.lua'
conky_lua.target = '~/modified-zenities/.config/conky/grouped_processes.lua'

vscode = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2 = { src = 'vscode', dst = '~/.cache/wallust/colors' }